const fakeData=[{
    "id": 1,
    "title": "Does Anybody Still Use JQuery?",
    "sort-description": "Do you like Cheese Whiz? Spray tan? Fake eyelashes? That's what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It's unreal, uncanny, makes you wonder if something is wrong,",
    "BlogContent": "Do you like Cheese Whiz? Spray tan? Fake eyelashes? That's what is Lorem Ipsum to many—it rubs them the wrong way, all the way. It's unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so we'd like our layouts and designs to be filled with real words, with thoughts that count, information that has value.The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, I'd say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.You begin with a text, you sculpt information, you chisel away what's not needed, you come to the point, make things clear, add value, you're a content person, you like words. Design is no afterthought, far from it, but it comes in a deserved second. Anyway, you still use Lorem Ipsum and rightly so, as it will always have a place in the web workers toolbox, as things happen, not always the way you like it, not always in the preferred order. Even if your less into design and more into content strategy you may find some redeeming value with, wait for it, dummy copy, no less.There's lot of hate out there for a text that amounts to little more than garbled words in an old language. The villagers are out there with a vengeance to get that Frankenstein, wielding torches and pitchforks, wanting to tar and feather it at the least, running it out of town in shame.One of the villagers, Kristina Halvorson from Adaptive Path, holds steadfastly to the notion that design can’t be tested without real content:",
    "image": "https://i.ibb.co/2cSqKtj/post-page-jpg.webp"
  }, {
    "id": 2,
    "title": "Annelise",
    "sort-description": "Tommen",
    "BlogContent": "atommen1@exblog.jp",
    "image": "Male"
  }, {
    "id": 3,
    "title": "Valina",
    "sort-description": "Goldine",
    "BlogContent": "vgoldine2@telegraph.co.uk",
    "image": "Bigender"
  }, {
    "id": 4,
    "title": "Jacklyn",
    "sort-description": "Voice",
    "BlogContent": "jvoice3@zdnet.com",
    "image": "Polygender"
  }, {
    "id": 5,
    "title": "Galen",
    "sort-description": "Topham",
    "BlogContent": "gtopham4@e-recht24.de",
    "image": "Genderqueer"
  }, {
    "id": 6,
    "title": "Xylia",
    "sort-description": "Sitlinton",
    "BlogContent": "xsitlinton5@squidoo.com",
    "image": "Polygender"
  }, {
    "id": 7,
    "title": "Kelby",
    "sort-description": "Spaight",
    "BlogContent": "kspaight6@businessinsider.com",
    "image": "Female"
  }, {
    "id": 8,
    "title": "Xymenes",
    "sort-description": "Picker",
    "BlogContent": "xpicker7@adobe.com",
    "image": "Agender"
  }, {
    "id": 9,
    "title": "Sunshine",
    "sort-description": "Glavias",
    "BlogContent": "sglavias8@google.com.au",
    "image": "Male"
  }, {
    "id": 10,
    "title": "Andris",
    "sort-description": "Btham",
    "BlogContent": "abtham9@latimes.com",
    "image": "Genderqueer"
  }, {
    "id": 11,
    "title": "Antonio",
    "sort-description": "Durram",
    "BlogContent": "adurrama@hibu.com",
    "image": "Genderqueer"
  }, {
    "id": 12,
    "title": "Modesta",
    "sort-description": "Brolechan",
    "BlogContent": "mbrolechanb@example.com",
    "image": "Genderfluid"
  }, {
    "id": 13,
    "title": "Montague",
    "sort-description": "Buston",
    "BlogContent": "mbustonc@tripod.com",
    "image": "Non-binary"
  }, {
    "id": 14,
    "title": "Helge",
    "sort-description": "Sherred",
    "BlogContent": "hsherredd@chron.com",
    "image": "Non-binary"
  }, {
    "id": 15,
    "title": "Chariot",
    "sort-description": "Butland",
    "BlogContent": "cbutlande@nymag.com",
    "image": "Female"
  }, {
    "id": 16,
    "title": "Bibbie",
    "sort-description": "Gustus",
    "BlogContent": "bgustusf@squarespace.com",
    "image": "Female"
  }, {
    "id": 17,
    "title": "Barbaraanne",
    "sort-description": "Ellingworth",
    "BlogContent": "bellingworthg@so-net.ne.jp",
    "image": "Male"
  }, {
    "id": 18,
    "title": "Garold",
    "sort-description": "Busch",
    "BlogContent": "gbuschh@comsenz.com",
    "image": "Non-binary"
  }, {
    "id": 19,
    "title": "Harry",
    "sort-description": "Braisted",
    "BlogContent": "hbraistedi@usa.gov",
    "image": "Genderqueer"
  }, {
    "id": 20,
    "title": "Darleen",
    "sort-description": "Crews",
    "BlogContent": "dcrewsj@mozilla.com",
    "image": "Polygender"
  }, {
    "id": 21,
    "title": "Kim",
    "sort-description": "Archbald",
    "BlogContent": "karchbaldk@arstechnica.com",
    "image": "Genderfluid"
  }, {
    "id": 22,
    "title": "Erie",
    "sort-description": "D'Cruze",
    "BlogContent": "edcruzel@indiatimes.com",
    "image": "Genderqueer"
  }, {
    "id": 23,
    "title": "Grissel",
    "sort-description": "Haddington",
    "BlogContent": "ghaddingtonm@hud.gov",
    "image": "Female"
  }, {
    "id": 24,
    "title": "Dawna",
    "sort-description": "De Mitri",
    "BlogContent": "ddemitrin@ocn.ne.jp",
    "image": "Genderqueer"
  }, {
    "id": 25,
    "title": "Rhianon",
    "sort-description": "Schwander",
    "BlogContent": "rschwandero@ftc.gov",
    "image": "Bigender"
  }, {
    "id": 26,
    "title": "Lindsy",
    "sort-description": "Robken",
    "BlogContent": "lrobkenp@toplist.cz",
    "image": "Male"
  }, {
    "id": 27,
    "title": "Daisey",
    "sort-description": "Diack",
    "BlogContent": "ddiackq@bandcamp.com",
    "image": "Bigender"
  }, {
    "id": 28,
    "title": "Stavro",
    "sort-description": "Scuse",
    "BlogContent": "sscuser@imdb.com",
    "image": "Bigender"
  }, {
    "id": 29,
    "title": "Eddy",
    "sort-description": "Trustram",
    "BlogContent": "etrustrams@fc2.com",
    "image": "Female"
  }, {
    "id": 30,
    "title": "Clementius",
    "sort-description": "Firk",
    "BlogContent": "cfirkt@clickbank.net",
    "image": "Female"
  }]

  export default fakeData;